FORMAT: 1A

# API一覧

# Group User

## 過去に購入したアイテム一覧API [GET /api/items/suitable]
一過去に購入したアイテム一覧API

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

+ Response 200 (application/json)

        {
            items: [
                {
                    item_code: "4521329132512",
                    category_id: 101107,
                    category_name: "ぬいぐるみ7",
                    country: "中国",
                    description: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも?",
                    ec_display_code: "4521329132512",
                    image_path: "/src/images/path/item2.png",
                    item_name: "ぬいぐるみ ドラパルト",
                    item_name_kana: null,
                    material: "素材",
                    rank: 3,
                    release_date: "2020-10-22",
                    size: "13×11.5×13:cm",
                    ticket_code: "9900000000001"
                },
                {
                    item_code: "4521329132513",
                    category_id: 101107,
                    category_name: "ぬいぐるみ7",
                    country: "中国",
                    description: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも?",
                    ec_display_code: "4521329132513",
                    image_path: "/src/images/path/item2.png",
                    item_name: "ぬいぐるみ ウッウ うのみの",
                    item_name_kana: "ぬいぐるみ ウッウ うのみの",
                    material: "素材",
                    rank: 3,
                    release_date: "2020-10-22",
                    size: "13×11.5×13:cm",
                    ticket_code: "9900000000001"
                }
            ],
            message: null,
            status: 200
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## 初期カテゴリ一覧API [GET /api/plays/{ticket_id}]
一初期カテゴリ一覧API

+ Parameters
    + ticket_id: 9900000000999 (number) - Id of ticket

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

+ Response 200 (application/json)

        {
            categories: [
                {
                    id: 1,
                    name: "玩具"
                },
                {
                    id: 2,
                    name: "ぬいぐるみ"
                }
            ]
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 404 (application/json)
    {
        error: {
            code: 4041,
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }


## カテゴリで、アイテム一覧API [GET /api/items-by-category/{category_id}]
一カテゴリで、アイテム一覧API

+ Parameters
    + category_id: 101107 (number) - Id of category

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

+ Response 200 (application/json)

        {
            items: [
                {
                    item_code: "4521329132512",
                    category_id: 101107,
                    category_name: "ぬいぐるみ",
                    country: "中国",
                    description: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも?",
                    ec_display_code: "4521329132512",
                    image_path: "/src/images/path/item2.png",
                    item_name: "ぬいぐるみ ウッウ うのみのすがた",
                    item_name_kana: null,
                    material: "素材",
                    rank: 3,
                    release_date: "2020-10-22",
                    size: "13×11.5×13:cm",
                    ticket_code: "9900000000999"
                },
                {
                    item_code: "4521329132513",
                    category_id: 101107,
                    category_name: "ぬいぐるみ",
                    country: "中国",
                    description: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも?",
                    ec_display_code: "4521329132513",
                    image_path: "/src/images/path/item3.png",
                    item_name: "ぬいぐるみ コオリッポ（アイスフェイス）",
                    item_name_kana: null,
                    material: "素材",
                    rank: 3,
                    release_date: "2020-10-22",
                    size: "13×11.5×13:cm",
                    ticket_code: "9900000000999"
                }
            ],
            message: null,
            code: 200
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 404 (application/json)
    {
        error: {
            code: 4041,
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }


## アイテム選択API [POST /api/plays/items/add]
一アイテム選択API

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

    + Body
        {
            item_code: "4521329132546"
        }

+ Response 200 (application/json)
    {
        status: 200,
        success: true
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## アイテム削除API [DELETE /api/items/delete]
一アイテム選択API

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

    + Attributes
        + item_code: `4521329132542` (string, required)

+ Response 200 (application/json)
    {
        status: 200,
        success: true
    }

+ Response 404 (application/json)
    {
        error: {
            code: 4041,
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }


## 在庫確認API [POST /api/plays/check]
一在庫確認API

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```
    + Body
        {
          data : [
              {
                  item_code: "4521329132549",
                  quantily: 2
              },
              {
                  item_code: "4521329132548",
                  quantily: 1
              }
          ]
        }
    + Schema
        {
            "type": "array",
        }

+ Response 200 (application/json)
    {
        status: 200,
        success: true
    }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 422 (application/json)
    {
        error: {
            code: "4221",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }


# Group Admin

## 認証API [POST /api/login]
一認証API

+ Request
    + Attributes
        + username: admin (required, optional) - Max-length = 50
        + password: 123456 (required, optional) - Max-length = 32

+ Response 200 (application/json)
    {
        data: {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4OVwvYXBpXC9sb2dpbiIsImlhdCI6MTYwMjc0NzExMCwiZXhwIjoxNjAzOTU2NzEwLCJuYmYiOjE2MDI3NDcxMTAsImp0aSI6IkU3ZHhOZnVPcTh0TmxsT0ciLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.egHdNxmbBdpk56f2YbGQpc6lMwWqG2b9k_TfjjzMESU",
            "token_type": "Bearer",
            "expires_in": 1209600
        },
        message: null,
        status: 200
    }

+ Response 401 (application/json)
    {
        error: {
            code: 4010,
            message: null
        }
    }
+ Response 422 (application/json)
    {
        error: {
            code: 4220,
            field: {
                "username": [
                    "validation.required"
                ],
                "password": [
                    "validation.required"
                ]
            }
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## インポートAPI [POST /api/items/import]
一インポートAPI

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```
    + Body
        {
          data : [
            {
               EC表示コード: "4521329132549",
               クラスコード: "101101",
               クラス名: "ぬいぐるみ",
               チケットJAN: "9900000000999",
               フリー項目01タイトル: "発売日",
               フリー項目01内容: "2020/10/10",
               フリー項目02タイトル: "サイズ",
               フリー項目02内容: "13×11.5×13:cm",
               フリー項目03タイトル: "素材",
               フリー項目03内容: "ポリエステル",
               フリー項目04タイトル: "原産国",
               フリー項目04内容: "中国",
               中分類コード: "101",
               中分類名: "玩具",
               商品ランク: "3",
               商品名: "エルフーンのみがわりぬいぐるみ",
               商品名カナ: "ｴﾙﾌｰﾝﾉﾐｶﾞﾜﾘﾇｲｸ",
               商品数: "100",
               商品画像: "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
               商品説明: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも",
               小分類コード: "1011",
               小分類名: "ぬいぐるみ",
               発売日: "2020/10/10",
               ＪＡＮコード: "9900000000999"
            },
            {
                EC表示コード: "4521329132549",
                クラスコード: "101102",
                クラス名: "ぬいぐるみ2",
                チケットJAN: "9900000000001",
                フリー項目01タイトル: "発売日",
                フリー項目01内容: "2020/10/11",
                フリー項目02タイトル: "サイズ",
                フリー項目02内容: "13×11.5×13:cm",
                フリー項目03タイトル: "素材",
                フリー項目03内容: "ポリエステル",
                フリー項目04タイトル: "原産国",
                フリー項目04内容: "中国",
                中分類コード: "102",
                中分類名: "玩具2",
                商品ランク: "3",
                商品名: "エルフーンのみがわりぬいぐるみ",
                商品名カナ: "ｴﾙﾌｰﾝﾉﾐｶﾞﾜﾘﾇｲｸ",
                商品数: "100",
                商品画像: "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
                商品説明: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも",
                小分類コード: "1012",
                小分類名: "ぬいぐるみ2",
                発売日: "2020/10/11",
                ＪＡＮコード: "9900000000001"
            }
        ]
        }

    + Schema
        {
            "type": "array",
        }

+ Response 200 (application/json)
    {
        status: 200,
        success: true
    }

+ Response 401 (application/json)
   {
       error: {
           code: "4010",
           message: null
       }
   }

+ Response 500 (application/json)
    {
        error: {
            code: 5002,
            message: null
        }
    }

## アイテム一覧API [GET /api/items]
一アイテム一覧API

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```
    + Attributes
        + per_page: 10 (number)
        + page: 1 (number)

+ Response 200 (application/json)

        {
            items: [
                {
                    item_code: "4521329132512",
                    category_id: 101107,
                    category_name: "ぬいぐるみ7",
                    country: "中国",
                    description: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも?",
                    ec_display_code: "4521329132512",
                    image_path: "/src/images/path/item2.png",
                    item_name: "ぬいぐるみ ドラパルト",
                    item_name_kana: null,
                    material: "素材",
                    rank: 3,
                    release_date: "2020-10-22",
                    size: "13×11.5×13:cm",
                    ticket_code: "9900000000001",
                    total_amount: 1212
                },
                {
                    item_code: "4521329132513",
                    category_id: 101107,
                    category_name: "ぬいぐるみ7",
                    country: "中国",
                    description: "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも?",
                    ec_display_code: "4521329132513",
                    image_path: "/src/images/path/item2.png",
                    item_name: "ぬいぐるみ ウッウ うのみの",
                    item_name_kana: "ぬいぐるみ ウッウ うのみの",
                    material: "素材",
                    rank: 3,
                    release_date: "2020-10-22",
                    size: "13×11.5×13:cm",
                    ticket_code: "9900000000001",
                    total_amount: 1212
                },
                current_page: 1,
                first_page_url: "https://rocktoon-ec-admin.fabbidev.com/api/items?page=1"
                from: 1
                last_page: 17
                last_page_url: "https://rocktoon-ec-admin.fabbidev.com/api/items?page=17"
                next_page_url: "https://rocktoon-ec-admin.fabbidev.com/api/items?page=2"
                path: "https://rocktoon-ec-admin.fabbidev.com/api/items"
                per_page: "10"
                prev_page_url: null
                to: 10
                total: 169
            ],
            message: null,
            status: 200
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## カテゴリリストAPI [GET /api/items/categories]
一カテゴリリストAPI

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```

+ Response 200 (application/json)
     {
         "data": {
             "categories": [
                 {
                     "id": 101101,
                     "name": "ぬいぐるみ"
                 },
                 {
                     "id": 101102,
                     "name": "ぬいぐるみ2"
                 },
                 {
                     "id": 101103,
                     "name": "ぬいぐるみ3"
                 },
                 {
                     "id": 101104,
                     "name": "ぬいぐるみ4"
                 }
             ]
         },
         "message": null,
         "status": 200
     }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## アイテム新規作成API [POST /api/items]
一アイテム新規作成API

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```
    + Attributes
        + item_name: ぬいぐるみ ウッウ うのみのすがた (string, required) - 名略
        + item_name_kana: ぬいぐるみ ウッウ うのみのすがた (string) - 名略カナ
        + rank: 3 (number, required) - ランク
        + image_path: `` (object, required) - プロフィール画像
            - file: 画像ファイル (string, required)
        + category_id: 101107 (number, required) - カテゴリID
        + release_date: `2020/10/22` (string) - 販売日
        + size: `13×11.5×13:cm` (string) - サイズ・重量
        + material: `素材` (string) - 素材
        + country: `中国` (string) - 原産国
        + total_amount: 1212 (number, required) - 現在の合計

+ Response 200 (application/json)
     {
         data: {
            item_code: "4521329132512",
            item_name: "ぬいぐるみ ウッウ うのみのすがた",
            category_id: "101107",
            country: "中国",
            id: 0,
            image_path: "imageItem/4521329132512.png",
            item_name_kana: "ぬいぐるみ ウッウ うのみのすがた",
            material: "素材",
            rank: "3",
            release_date: "2020/10/22",
            size: "13×11.5×13:cm",
            total_amount: "1212"
         },
         message: null,
         status: 200
     }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 422 (application/json)
    {
        error: {
            code: 4220,
            field: {
                item_code: [
                    "validation.required"
                ],
                item_name: [
                    "validation.required"
                ],
                item_name_kana: [
                    "validation.max.string"
                ],
                category_id: [
                    "validation.required"
                ],
                total_amount: [
                    "validation.required"
                ],
                material: [
                    "validation.max.string"
                ],
                country: [
                    "validation.max.string"
                ]
            }
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5003",
            message: null
        }
    }


## アイテム編集API [GET /api/items/{code}/edit]
一アイテム編集API

+ Parameters
    + code: 9900000000001 - code of item

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```

+ Response 200 (application/json)
    {
        "data": {
            "item_code": "9900000000001",
            "ticket_code": "9900000000001",
            "category_id": 101102,
            "item_name": "エルフーンのみがわりぬいぐるみ",
            "item_name_kana": "ｴﾙﾌｰﾝﾉﾐｶﾞﾜﾘﾇｲｸ",
            "rank": 5,
            "image_path": "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
            "ec_display_code": "4521329132549",
            "release_date": "2020-10-01",
            "description": "わざ「みがわり」を使った時に登場する、人形のようなものをモチーフにしたぬいぐるみが登場。君の「みがわり」になってくれるかも",
            "size": "13×11.5×13:cm",
            "material": "ポリエステル",
            "country": "中国",
            "total_amount": 100
        },
        "message": null,
        "status": 200
    }

+ Response 401 (application/json)
    {
        "error": {
            "code": "4010",
            "message": null
        }
    }

+ Response 404 (application/json)
    {
        error: {
            code: "4041",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## アイテム編集API [POST /api/items/{code}]
一アイテム編集API

+ Parameters
    + code: 1 - code of item

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```
    + Attributes
        + item_name: ぬいぐるみ ウッウ うのみのすがた (string, required) - 名略
        + item_name_kana: ぬいぐるみ ウッウ うのみのすがた (string) - 名略カナ
        + rank: 3 (number, required) - ランク
        + image_path: `` (object, required) - プロフィール画像
            - file: 画像ファイル (string, required)
        + category_id: 101107 (number, required) - カテゴリID
        + release_date: `2020/10/22` (string) - 販売日
        + size: `13×11.5×13:cm` (string) - サイズ・重量
        + material: `素材` (string) - 素材
        + country: `中国` (string) - 原産国
        + total_amount: 1212 (number, required) - 現在の合計

+ Response 200 (application/json)
    {
        status: 200,
        success: true
    }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5004",
            message: null
        }
    }

## アイテム削除API [DELETE /api/items/{code}]
一アイテム削除API

+ Parameters
    + code: 1465643556 - code of item

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```

+ Response 200 (application/json)
    {
        status: 200,
        success: true
    }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 404 (application/json)
    {
        error: {
            code: "4041",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## アイテムエクスポートAPI [POST /api/items/export]
一アイテムエクスポートAPI

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```
    + Body
        {
          ids : [1, 2]
        }

    + Schema
        {
            "type": "array",
        }

+ Response 200 (application/json)

    {
        "data": {
            "plays": [
                [
                    "20201027104121",
                    1,
                    10,
                    1,
                    930,
                    " ",
                    "001",
                    " ",
                    1,
                    9,
                    1,
                    930,
                    930,
                    930,
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    930,
                    930,
                    900,
                    "",
                    "ＣＬＣ",
                    "20201027",
                    " ",
                    10101,
                    0,
                    930,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    " ",
                    " ",
                    " ",
                    " ",
                    " ",
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    300,
                    0,
                    1,
                    3000,
                    300,
                    3300,
                    "9900000000012",
                    "",
                    "",
                    "",
                    "9900000000012",
                    "詰め放題チケット",
                    "",
                    "PC",
                    "ﾋﾟｰｽ",
                    1,
                    1,
                    "JPY",
                    "JPY",
                    0,
                    3300,
                    0,
                    3300,
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    3300,
                    300,
                    0,
                    0,
                    0
                ],
                [
                    "20201027104121",
                    2,
                    10,
                    1,
                    930,
                    " ",
                    "001",
                    " ",
                    2,
                    0,
                    1,
                    930,
                    930,
                    930,
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    930,
                    930,
                    900,
                    "",
                    "ＣＬＣ",
                    "20201027",
                    " ",
                    10101,
                    0,
                    930,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    " ",
                    " ",
                    " ",
                    " ",
                    " ",
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    300,
                    0,
                    12,
                    3000,
                    300,
                    3300,
                    "9900000000012",
                    "",
                    "",
                    "",
                    "9900000000012",
                    "エルフーンのみがわりぬいぐるみ",
                    "",
                    "PC",
                    "ﾋﾟｰｽ",
                    1,
                    12,
                    "JPY",
                    "JPY",
                    0,
                    0,
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    3300,
                    300,
                    0,
                    0,
                    0
                ],
                [
                    "20201027104121",
                    3,
                    10,
                    1,
                    930,
                    " ",
                    "001",
                    " ",
                    3,
                    0,
                    1,
                    930,
                    930,
                    930,
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    930,
                    930,
                    900,
                    "",
                    "ＣＬＣ",
                    "20201027",
                    " ",
                    10101,
                    0,
                    930,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    " ",
                    " ",
                    " ",
                    " ",
                    " ",
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    300,
                    0,
                    3,
                    3000,
                    300,
                    3300,
                    "9900000000013",
                    "",
                    "",
                    "",
                    "9900000000013",
                    "わわわわわわわわわわわわわわわわわわ",
                    "",
                    "PC",
                    "ﾋﾟｰｽ",
                    1,
                    3,
                    "JPY",
                    "JPY",
                    0,
                    0,
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    3300,
                    300,
                    0,
                    0,
                    0
                ],
                [
                    "20201027104121",
                    4,
                    10,
                    1,
                    930,
                    " ",
                    "001",
                    " ",
                    1,
                    9,
                    1,
                    930,
                    930,
                    930,
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    930,
                    930,
                    900,
                    "",
                    "ＣＬＣ",
                    "20201027",
                    " ",
                    10101,
                    0,
                    930,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    " ",
                    " ",
                    " ",
                    " ",
                    " ",
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    300,
                    0,
                    1,
                    3000,
                    300,
                    3300,
                    "1234567899887",
                    "",
                    "",
                    "",
                    "1234567899887",
                    "詰め放題チケット",
                    "",
                    "PC",
                    "ﾋﾟｰｽ",
                    1,
                    1,
                    "JPY",
                    "JPY",
                    0,
                    3300,
                    0,
                    3300,
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    3300,
                    300,
                    0,
                    0,
                    0
                ],
                [
                    "20201027104121",
                    5,
                    10,
                    1,
                    930,
                    " ",
                    "001",
                    " ",
                    2,
                    0,
                    1,
                    930,
                    930,
                    930,
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    930,
                    930,
                    900,
                    "",
                    "ＣＬＣ",
                    "20201027",
                    " ",
                    10101,
                    0,
                    930,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    " ",
                    " ",
                    " ",
                    " ",
                    " ",
                    "",
                    " ",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    300,
                    0,
                    9,
                    3000,
                    300,
                    3300,
                    "9900000000013",
                    "",
                    "",
                    "",
                    "9900000000013",
                    "aaaaaaaaaaaa",
                    "",
                    "PC",
                    "ﾋﾟｰｽ",
                    1,
                    9,
                    "JPY",
                    "JPY",
                    0,
                    0,
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    3300,
                    300,
                    0,
                    0,
                    0
                ]
            ]
        },
        "message": null,
        "status": 200
    }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## プレイ一覧API [GET /api/plays]
一プレイ一覧API

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

+ Response 200 (application/json)

        {
            "data": {
                "plays": {
                    "current_page": 1,
                    "data": [
                        {
                            "id": 1,
                            "pol_user_id": "1234567891",
                            "ticket_code": "9900000000012",
                            "start_at": null,
                            "finish_at": "2020-10-23 14:48:02",
                            "total_ticket_ball": null,
                            "total_played_ball": null,
                            "status": 1,
                            "total_item": 15,
                            "items": [
                                {
                                    "item_code": "9900000000012",
                                    "id": 1,
                                    "play_id": 1,
                                    "ticket_code": "4521329132549",
                                    "category_id": 111,
                                    "item_name": "エルフーンのみがわりぬいぐるみ",
                                    "item_name_kana": null,
                                    "rank": 5,
                                    "image_path": "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
                                    "ec_display_code": null,
                                    "release_date": null,
                                    "description": null,
                                    "size": null,
                                    "material": null,
                                    "country": null,
                                    "quantity": 12
                                },
                                {
                                    "item_code": "9900000000013",
                                    "id": 2,
                                    "play_id": 1,
                                    "ticket_code": "4521329132549",
                                    "category_id": 123,
                                    "item_name": "わわわわわわわわわわわわわわわわわわ",
                                    "item_name_kana": null,
                                    "rank": 3,
                                    "image_path": "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
                                    "ec_display_code": null,
                                    "release_date": null,
                                    "description": null,
                                    "size": null,
                                    "material": null,
                                    "country": null,
                                    "quantity": 3
                                }
                            ]
                        }
                    ],
                    "first_page_url": "http://localhost:8089/api/plays?page=1",
                    "from": 1,
                    "last_page": 1,
                    "last_page_url": "http://localhost:8089/api/plays?page=1",
                    "next_page_url": null,
                    "path": "http://localhost:8089/api/plays",
                    "per_page": 10,
                    "prev_page_url": null,
                    "to": 1,
                    "total": 1
                }
            },
            "message": null,
            "status": 200
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }

## プレイ詳細API [GET /api/plays/{id}]
一プレイ詳細API
+ Parameters
    + id: 1 - id of play

+ Request

    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        ```

+ Response 200 (application/json)

        {
            "data": {
                "play": {
                    "id": 1,
                    "pol_user_id": "1234567891",
                    "ticket_code": "9900000000012",
                    "start_at": null,
                    "finish_at": "2020-10-23 14:48:02",
                    "total_ticket_ball": null,
                    "total_played_ball": null,
                    "status": 1,
                    "total_item": 15,
                    "items": [
                        {
                            "item_code": "9900000000012",
                            "id": 1,
                            "play_id": 1,
                            "ticket_code": "4521329132549",
                            "category_id": 111,
                            "item_name": "エルフーンのみがわりぬいぐるみ",
                            "item_name_kana": null,
                            "rank": 5,
                            "image_path": "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
                            "ec_display_code": null,
                            "release_date": null,
                            "description": null,
                            "size": null,
                            "material": null,
                            "country": null,
                            "quantity": 12
                        },
                        {
                            "item_code": "9900000000013",
                            "id": 2,
                            "play_id": 1,
                            "ticket_code": "4521329132549",
                            "category_id": 123,
                            "item_name": "わわわわわわわわわわわわわわわわわわ",
                            "item_name_kana": null,
                            "rank": 3,
                            "image_path": "https://www.pokemoncenter-online.com/static/product_image/4521329132549/4521329132549.jpg",
                            "ec_display_code": null,
                            "release_date": null,
                            "description": null,
                            "size": null,
                            "material": null,
                            "country": null,
                            "quantity": 3
                        }
                    ]
                }
            },
            "message": null,
            "status": 200
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
            message: null
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
            message: null
        }
    }
