FORMAT: 1A

# API一覧

## 認証API [POST /api/login]
一認証API

+ Request
    + Attributes
        + username: admin (required) - Max-length = 32
        + password: 123456 (required) - Max-length = 32

+ Response 200 (application/json)
    {
        data: {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4OVwvYXBpXC9sb2dpbiIsImlhdCI6MTYwMjc0NzExMCwiZXhwIjoxNjAzOTU2NzEwLCJuYmYiOjE2MDI3NDcxMTAsImp0aSI6IkU3ZHhOZnVPcTh0TmxsT0ciLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.egHdNxmbBdpk56f2YbGQpc6lMwWqG2b9k_TfjjzMESU",
            "token_type": "Bearer",
            "expires_in": 1209600
        },
        status: 200
    }

+ Response 401 (application/json)
    {
        error: {
            code: 4010,
        }
    }
+ Response 422 (application/json)
    {
        error: {
            code: 4220,
            field: {
                "username": [
                    "validation.required"
                ],
                "password": [
                    "validation.required"
                ]
            }
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001"
        }
    }
    
## Get user API [GET /api/user]
Get user API

+ Request
    + Headers
        ```
        Content-type: application/json,charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Authorization: Bearer token
        ```

+ Response 200 (application/json)

        {
            "user": {
                "name": "sample name",
                "address": "sample address",
                "dob": "1990-10-23"
            },
            status: 200
        }

+ Response 401 (application/json)
    {
        error: {
            code: "4010",
        }
    }

+ Response 500 (application/json)
    {
        error: {
            code: "5001",
        }
    }
